repos: 
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0
  hooks:
  - id: ruff
    args: [--exit-non-zero-on-fix, --fix]
  - id: ruff-format
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    types_or: [python, markdown]
    additional_dependencies: [tomli]
- repo: local
  hooks:
  # mypy is slow, so change it to manual when needed
  - id: mypy
    # note: assumes python env is setup and activated
    name: mypy
    entry: mypy
    language: system
    pass_filenames: false
    args: ["--ignore-missing-imports", "."]