name: jobspider
channels:
  - conda-forge
dependencies:
  - beautifulsoup4==4.12.2
  - colorlog==6.8.0
  - fake-useragent==1.4.0
  - pandas==2.1.3
  - requests==2.31.0
  - selenium==4.15.2
  - python==3.10.6
  - ruff
  - pre-commit
